# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountCreateDate',
            field=models.DateTimeField(null=True),
        ),
    ]
