# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelDB', '0002_auto_20171222_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountCreateDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
